name: point-of-sale-CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy json5 pytest
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test_on_unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          export PYTHONPATH=$(pwd)
          echo $PYTHONPATH
          pytest
      - name: test_on_windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $Env:PYTHONPATH = Get-Location
          pytest
